version: '3.8'

services:
  deepdub-proxy:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DEMO_MODE=true
      # Uncomment and set for production:
      # - DEEPDUB_API_KEY=your_api_key_here
      # - DEEPDUB_VOICE_PROMPT_ID=your_voice_prompt_id_here
      # - VAPI_SECRET=your_custom_secret
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
