version: '3.8'

services:
  elevenlabs-proxy:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DEMO_MODE=true
      # Uncomment and set for production:
      # - ELEVENLABS_API_KEY=your_api_key_here
      # - ELEVENLABS_VOICE_ID=your_voice_id_here
      # - ELEVENLABS_MODEL_ID=eleven_multilingual_v2
      # - VAPI_SECRET=your_custom_secret
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
