services:
  - type: web
    name: elevenlabs-vapi-proxy
    runtime: docker
    plan: standard  # Using standard plan for Docker support
    branch: elevenLabsModel
    healthCheckPath: /
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ELEVENLABS_API_KEY
        sync: false  # Set this in Render dashboard
      - key: ELEVENLABS_VOICE_ID
        sync: false  # Set this in Render dashboard
      - key: ELEVENLABS_MODEL_ID
        value: eleven_multilingual_v2  # Default value
      - key: VAPI_SECRET
        value: elevenlabs-secret-2025  # Default value
      - key: DEMO_MODE
        value: false
      - key: PORT
        value: 5000
