services:
  - type: web
    name: deepdub-vapi-proxy
    runtime: docker
    plan: standard  # Using standard plan for Docker support
    branch: main
    healthCheckPath: /
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DEEPDUB_API_KEY
        sync: false  # Set this in Render dashboard
      - key: DEEPDUB_VOICE_PROMPT_ID
        sync: false  # Set this in Render dashboard
      - key: VAPI_SECRET
        value: deepdub-secret-2025  # Default value
      - key: DEMO_MODE
        value: false
      - key: PORT
        value: 5000